application: nlight-reader
version: 1
runtime: python
api_version: 1

handlers:
- url: /api/0/(.*)
  script: grapi.py
- url: (/|/index.html)
  static_files: static/index.html
  upload: static/(.*)
- url: /img
  static_dir: img/
- url: /stylesheets
  static_dir: stylesheets/
- url: /js
  static_dir: js/
